name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      ADMIN_REGISTRATION_CODE: ${{ secrets.ADMIN_REGISTRATION_CODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set DATA_DIR dynamically
        run: |
          echo "DATA_DIR=$(pwd)/data" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Change to project directory and run tests
        run: cd $GITHUB_WORKSPACE && DATA_DIR=data go test -v ./...

